### Service Document
GET http://localhost:4004/browse

### Service $metadata document
GET http://localhost:4004/browse/$metadata

### Browsing Games
GET http://localhost:4004/browse/Games?


### Browsing Publishers
GET http://localhost:4004/admin/Publishers?


### Browsing Games
GET http://localhost:4004/admin/Games?



### Create new Publisher
POST http://localhost:4004/admin/Publishers
Content-Type: application/json

{ "name":"Sony"}

### Create new Game
POST http://localhost:4004/admin/Games
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true


{ 
    "name":"snake",
    "description": "classic game",
    "rating": "30.0",
    "image": "",
    "ID": 6779,
    "price": "3.00"
}
### Delete  Game
DELETE  http://localhost:4004/browse/Games(109)
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true

### Delete  Game as admin
DELETE  http://localhost:4004/admin/Games(109)
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true
