### Service Document
GET http://localhost:4004/browse

### Service $metadata document
GET http://localhost:4004/browse/$metadata

### Browsing Games
GET http://localhost:4004/browse/Games?
# &$select=title,author
# &$expand=currency
# &sap-language=de

### Browsing Publishers
GET http://localhost:4004/admin/Publishers?
# &$select=name,dateOfBirth,placeOfBirth
# &$expand=books($select=title;$expand=currency)
# &$filter=ID eq 101
# &sap-language=de

### Browsing Games
GET http://localhost:4004/admin/Games?
# &$select=name,dateOfBirth,placeOfBirth
# &$expand=books($select=title;$expand=currency)
# &$filter=ID eq 101
# &sap-language=de


### Create new Publisher
POST http://localhost:4004/admin/Publishers
Content-Type: application/json

{ "name":"Sony"}

### Create new Game
POST http://localhost:4004/admin/Games
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true


{ 
    "name":"snake",
    "description": "classic game",
    "rating": "30.0",
    "image": "",
    "ID": 6779,
    "price": "3.00"
}
### Delete  Game
DELETE  http://localhost:4004/admin/Games(109)
Content-Type: application/json;charset=UTF-8;IEEE754Compatible=true

